ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true                       # planární robot :contentReference[oaicite:10]{index=10}
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false

    imu0: /imu
    imu0_config: [false, false, false,
                  false, false, true,     # yaw
                  false, false, false,
                  false, false, true,     # yaw rate
                  false, false, false]    # accel typicky vypnuto pro 2D diff-drive start
    imu0_differential: false
    imu0_remove_gravitational_acceleration: false