scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: keep_270deg
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 0.0
        upper_angle: 1.570796